=== lijtforgithub/study-java/src/main/resources/pp/catchTaskXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/catchTaskXML"
	xmlns:tns="http://www.example.org/catchTaskXML" elementFormDefault="qualified">
	
	<xsd:element name="catchTasks">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="task" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:choice>
							<xsd:element name="dbVist">
								<xsd:complexType>
									<xsd:all>
										<xsd:element name="platformDBAlias" type="xsd:string"/>
									</xsd:all>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="jmsVist">
								<xsd:complexType>
									<xsd:all>
										<xsd:element name="jmsURL" type="xsd:string"/>
										<xsd:element name="queueName" type="xsd:string"/>
									</xsd:all>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="wsVist">
								<xsd:complexType>
									<xsd:all>
										<xsd:element name="webservice" type="xsd:string"/>
									</xsd:all>
								</xsd:complexType>
							</xsd:element>
						</xsd:choice>
						<xsd:attribute name="name" type="xsd:string" use="required"/>
						<xsd:attribute name="class" type="xsd:string" use="required"/>
						<xsd:attribute name="taskCarrierImpl" type="xsd:string"/>
						<xsd:attribute name="dataProviderNode" type="xsd:long" use="required"/>
						<xsd:attribute name="dataModelNode" type="xsd:long" use="required"/>
						<xsd:attribute name="targetNode" type="xsd:string" use="required"/>
						<xsd:attribute name="frequency" type="xsd:long" use="required"/>
						<xsd:attribute name="priority" type="xsd:long" use="required"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== lijtforgithub/study-java/src/main/resources/pp/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<catchTasks xmlns="http://www.example.org/catchTaskXML"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/catchTaskXML catchTaskXML.xsd ">
	<task name="部门数据" class="com.ving.newWeb.department.CatchDepartmentDataImpl"
		taskCarrierImpl="自己实现的采集情况" dataProviderNode="1" dataModelNode="7"
		targetNode="7 ,3,4 " frequency="10" priority="1">
		<dbVist>
			<platformDBAlias>exchangeBase</platformDBAlias>
		</dbVist>
	</task>
	<task name="办件数据" class="com.ving.newWeb.department.CatchCaseDataImpl"
		taskCarrierImpl="自己实现的采集情况" dataProviderNode="1" dataModelNode="7"
		targetNode="7,3,4" frequency="10" priority="1">
		<jmsVist>
			<jmsURL>http://192.168.0.125:61616</jmsURL>
			<queueName>demoQueue</queueName>
		</jmsVist>
	</task>
	<task name="补办件数据" class="com.ving.newWeb.department.CatchCaseDataImpl"
		taskCarrierImpl="自己实现的采集情况" dataProviderNode="1" dataModelNode="7"
		targetNode="7,3,4" frequency="10" priority="1">
		<wsVist>
			<webservice>http://192.168.0.125:8088/ExchangeDataWS?wsdl</webservice>
		</wsVist>
	</task>
</catchTasks>
